### ISSUE TITLE
'IndoNLGTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by fjoeda** [SamuelCahyawijaya/indobenchmark-toolkit#3]
Hello, I currently tried to fine-tune the IndoGPT2 model using transformers package form huggingface. It asked me to use the IndoNLGTokenizer for the tokenizer but when I run the sample code to encode the text, it gave me `AttributeError: 'IndoNLGTokenizer' object has no attribute 'sp_model'`. 

the sample code
```
from indobenchmark import IndoNLGTokenizer
tokenizer = IndoNLGTokenizer.from_pretrained('indobenchmark/indogpt')
inputs = tokenizer.prepare_input_for_generation('hai, bagaimana kabar', model_type='indogpt', return_tensors='pt')
```

Installed related packages on Google Colab: 
- `transformers==4.34.0`
- `torch==2.0.1+cu118`
- `sentencepiece==0.1.99`

Is there any way to resolve the error?

**Comment by fjoeda** [comment]
The current solution is downgrade the `transformers` and `tokenizers` version.
- `transformers==4.33.1`
- `tokenizers==0.13.3`

**Comment by Putnug1122** [comment]
downgrading not working for me 😞 

```py
from transformers import GPT2LMHeadModel
from indobenchmark import IndoNLGTokenizer

gpt_model = GPT2LMHeadModel.from_pretrained('indobenchmark/indogpt')
tokenizer = IndoNLGTokenizer.from_pretrained('indobenchmark/indogpt')
#inputs = tokenizer.prepare_input_for_generation('hai, bagaimana kabar', model_type='indogpt', return_tensors='pt')
model = gpt_model
model
```
```
transformers                             4.33.1
tokenizers                               0.13.3
```

**Comment by Mettikodeva** [comment]
you can check my pull request, hope it works!

**Comment by SamuelCahyawijaya** [comment]
@Mettikodeva : thank you for the PR. I have merged the code, it works well when I tested it. 

@Putnug1122 @fjoeda : I am sorry for the late reply, you can try reinstalling the package from the [master` branch](https://github.com/indobenchmark/indobenchmark-toolkit) or the [latest version on pypi](https://pypi.org/project/indobenchmark-toolkit/).
